[package]
name = "pcbfapi"
version = "0.3.0"
edition = "2024"
repository = "https://github.com/David207025/PCB-Forge.git"
authors = ["David207025"]
description = "PCBF API is the background task used by the PCB-Forge VS-Code extension. This API manages the PDF creation and BOM storage/generation"
homepage = "https://github.com/David207025/PCB-Forge.git"

[package.metadata.wix]
upgrade-guid = "61493CE6-9B9A-4E7E-BFBD-FCAE378ED36F"
path-guid = "654E5F75-1439-49AC-B81F-BFA57EC704F1"
license = false
eula = false



[[bin]]
name = "pcbfapi"
path = "src/main.rs"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tray-icon = "0.19"
tao = "0.30"
image = "0.25" # <-- Add this for loading JPEG/PNG

